"""FlashMD: Chunked dense kernel for explicit solvent (LJ + PME Direct Space).

Eliminates the HBM bandwidth bottleneck by tiling the N² pair computation
into L2-cache-resident T×T blocks. Uses jax.checkpoint (remat) to discard
forward-pass intermediates and recompute them during the backward pass,
keeping all (T,T) working arrays in L2/SRAM instead of HBM.

This kernel uses precomputed dense exclusion matrices generated by
PaddedSystem to properly scale intramolecular interactions (e.g. 1-4
scaling and 1-2/1-3 complete exclusions for water).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import jax
import jax.numpy as jnp
from jax.scipy.special import erfc

from proxide.physics.constants import COULOMB_CONSTANT

if TYPE_CHECKING:
    from jax_md.util import Array
    from prolix.padding import PaddedSystem


def _safe_norm(x: Array, axis: int = -1, eps: float = 1e-12) -> Array:
    """Safe norm avoiding NaN gradients at zero."""
    return jnp.sqrt(jnp.sum(x ** 2, axis=axis) + eps)


def chunked_explicit_nonbonded_energy(
    positions: Array,
    charges: Array,
    sigmas: Array,
    epsilons: Array,
    atom_mask: Array,
    dense_excl_scale_vdw: Array,
    dense_excl_scale_elec: Array,
    T: int = 256,
    soft_core_lambda: float = 1.0,
    pme_alpha: float = 0.0,
) -> Array:
    """Fused LJ + Direct-space Coulomb energy in one tiled O(N²) pass.

    Uses dense exclusion matrices. jax.checkpoint ensures intermediates 
    stay in L2 cache.

    Args:
        positions: (N, 3) atom positions.
        charges: (N,) partial charges.
        sigmas: (N,) LJ sigma.
        epsilons: (N,) LJ epsilon.
        atom_mask: (N,) boolean mask.
        dense_excl_scale_vdw: (N, N) precomputed VDW exclusion scale matrix.
        dense_excl_scale_elec: (N, N) precomputed Coulomb exclusion scale matrix.
        T: Tile size. Must evenly divide N.
        soft_core_lambda: Soft-core coupling (1.0=standard LJ).
        pme_alpha: Ewald alpha for direct space damping. If 0, uses regular Coulomb.

    Returns:
        Scalar total nonbonded energy (kcal/mol).
    """
    N = positions.shape[0]
    n_tiles = N // T

    lam = jnp.float32(soft_core_lambda)
    alpha_sc = jnp.float32(0.5)
    soft_term = alpha_sc * jnp.maximum(1.0 - lam, jnp.float32(1e-8))

    def tile_energy_outer(carry, j_idx):
        start = j_idx * T

        @jax.checkpoint
        def _compute_tile_inner(pos, start_idx):
            r_j = jax.lax.dynamic_slice(pos, (start_idx, 0), (T, 3))
            q_j = jax.lax.dynamic_slice(charges, (start_idx,), (T,))
            s_j = jax.lax.dynamic_slice(sigmas, (start_idx,), (T,))
            e_j = jax.lax.dynamic_slice(epsilons, (start_idx,), (T,))
            m_j = jax.lax.dynamic_slice(atom_mask, (start_idx,), (T,))

            # Slice the dense exclusion matrices for this tile
            vdw_scale_tile = jax.lax.dynamic_slice(dense_excl_scale_vdw, (0, start_idx), (N, T))
            elec_scale_tile = jax.lax.dynamic_slice(dense_excl_scale_elec, (0, start_idx), (N, T))

            # Shared distances (N, T)
            dr = pos[:, None, :] - r_j[None, :, :]
            dist_sq = jnp.sum(dr ** 2, axis=-1) + 1e-10
            dist = jnp.sqrt(dist_sq)

            # Self-exclusion
            i_indices = jnp.arange(N)[:, None]
            j_indices = jnp.arange(T)[None, :] + start_idx
            not_self = (i_indices != j_indices).astype(jnp.float32)

            # Pair mask
            pair_mask = (atom_mask[:, None] & m_j[None, :]).astype(jnp.float32) * not_self

            # --- LJ ---
            sig_ij = 0.5 * (sigmas[:, None] + s_j[None, :])
            sig_ij_safe = jnp.where(
                pair_mask > 0, jnp.maximum(sig_ij, 1e-4), 1.0
            )
            eps_ij = jnp.sqrt(jnp.maximum(
                epsilons[:, None] * e_j[None, :], 0.0
            ))
            r_over_sig = dist / sig_ij_safe
            r6 = r_over_sig ** 6
            D = soft_term + r6 + 1e-12
            e_lj = 4.0 * eps_ij * lam * (1.0 / (D * D) - 1.0 / D)
            e_lj = jnp.where(pair_mask > 0, e_lj * vdw_scale_tile, 0.0)

            # --- Coulomb ---
            qq = charges[:, None] * q_j[None, :] * COULOMB_CONSTANT
            
            # PME Direct Space damping: erfc(alpha * r) / r
            # Standard Coulomb: 1 / r
            if pme_alpha > 0.0:
                coulomb_term = qq * erfc(pme_alpha * dist) / dist
            else:
                coulomb_term = qq / dist
                
            e_coul = jnp.where(pair_mask > 0, coulomb_term * elec_scale_tile, 0.0)

            # 0.5× for LJ/Coulomb double-count (since we loop over all pairs N x N)
            return 0.5 * jnp.sum(e_lj) + 0.5 * jnp.sum(e_coul)

        tile_e = _compute_tile_inner(positions, start)
        return carry + tile_e, None

    total_energy, _ = jax.lax.scan(
        tile_energy_outer,
        jnp.float32(0.0),
        jnp.arange(n_tiles),
    )

    return total_energy


def flash_explicit_forces(
    sys: PaddedSystem,
    T: int = 256,
    soft_core_lambda: float = 1.0,
    pme_alpha: float = 0.0,
) -> Array:
    """Compute explicit solvent nonbonded forces via FlashMD architecture.

    Returns:
        Forces (N, 3) in kcal/mol/Å. Zero for padded atoms.
    """
    safe_charges = jnp.where(sys.atom_mask, sys.charges, jnp.float32(0.0))
    safe_sigmas = jnp.where(sys.atom_mask, sys.sigmas, jnp.float32(1.0))
    safe_epsilons = jnp.where(sys.atom_mask, sys.epsilons, jnp.float32(0.0))
    
    # Ensure exclusion matrices are precomputed
    if sys.dense_excl_scale_vdw is None or sys.dense_excl_scale_elec is None:
        raise ValueError(
            "Dense exclusion matrices not found. Call precompute_dense_exclusions(sys) first."
        )

    def _total_energy(positions):
        return chunked_explicit_nonbonded_energy(
            positions,
            safe_charges,
            safe_sigmas,
            safe_epsilons,
            sys.atom_mask,
            sys.dense_excl_scale_vdw,
            sys.dense_excl_scale_elec,
            T=T,
            soft_core_lambda=soft_core_lambda,
            pme_alpha=pme_alpha,
        )

    forces = -jax.grad(_total_energy)(sys.positions)
    return forces * sys.atom_mask[:, None]
