"""FlashMD: Chunked dense kernel for explicit solvent (LJ + PME Direct Space).

Eliminates the HBM bandwidth bottleneck by tiling the N² pair computation
into L2-cache-resident T×T blocks. Uses jax.checkpoint (remat) to discard
forward-pass intermediates and recompute them during the backward pass,
keeping all (T,T) working arrays in L2/SRAM instead of HBM.

This kernel uses precomputed dense exclusion matrices generated by
PaddedSystem to properly scale intramolecular interactions (e.g. 1-4
scaling and 1-2/1-3 complete exclusions for water).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import equinox as eqx
import jax
import jax.numpy as jnp
from jax.scipy.special import erfc
from jaxtyping import Array
from proxide.physics.constants import COULOMB_CONSTANT

from prolix.padding import PaddedSystem
from prolix.physics import explicit_corrections, pbc
from prolix.physics.electrostatic_methods import ElectrostaticMethod
from prolix.physics.pme import make_spme_energy_fn, spme_background_energy
from prolix.physics.efa_coulomb import (
    efa_lebedev_coulomb_energy,
    efa_lebedev_params,
)
from prolix.physics.rff_coulomb import (
    efa_exclusion_correction,
    efa_short_range_erfc_energy,
    erfc_rff_coulomb_energy_diff,
    rff_frequency_sample,
)
from prolix.utils import topology

if TYPE_CHECKING:
    from jax_md.util import Array

    from prolix.padding import PaddedSystem


def _safe_norm(x: Array, axis: int = -1, eps: float = 1e-12) -> Array:
    """Safe norm avoiding NaN gradients at zero."""
    return jnp.sqrt(jnp.sum(x ** 2, axis=axis) + eps)


def chunked_explicit_nonbonded_energy(
    positions: Array,
    charges: Array,
    sigmas: Array,
    epsilons: Array,
    atom_mask: Array,
    sys: PaddedSystem, # Pass whole sys for sparse exclusions
    T: int = 256,
    soft_core_lambda: float = 1.0,
    pme_alpha: float = 0.0,
) -> Array:
    """Fused LJ + Direct-space Coulomb energy in one tiled O(N²) pass.

    Uses dense exclusion matrices. jax.checkpoint ensures intermediates
    stay in L2 cache.

    Args:
        positions: (N, 3) atom positions.
        charges: (N,) partial charges.
        sigmas: (N,) LJ sigma.
        epsilons: (N,) LJ epsilon.
        atom_mask: (N,) boolean mask.
        dense_excl_scale_vdw: (N, N) precomputed VDW exclusion scale matrix.
        dense_excl_scale_elec: (N, N) precomputed Coulomb exclusion scale matrix.
        T: Tile size. Must evenly divide N.
        soft_core_lambda: Soft-core coupling (1.0=standard LJ).
        pme_alpha: Ewald alpha for direct space damping. If 0, uses regular Coulomb.

    Returns:
        Scalar total nonbonded energy (kcal/mol).
    """
    N = positions.shape[0]
    n_tiles = N // T

    lam = jnp.float32(soft_core_lambda)
    alpha_sc = jnp.float32(0.5)
    soft_term = alpha_sc * jnp.maximum(1.0 - lam, jnp.float32(1e-8))

    def tile_energy_outer(carry, j_idx):
        start = j_idx * T

        @jax.checkpoint
        def _compute_tile_inner(pos, start_idx):
            r_j = jax.lax.dynamic_slice(pos, (start_idx, 0), (T, 3))
            q_j = jax.lax.dynamic_slice(charges, (start_idx,), (T,))
            s_j = jax.lax.dynamic_slice(sigmas, (start_idx,), (T,))
            e_j = jax.lax.dynamic_slice(epsilons, (start_idx,), (T,))
            m_j = jax.lax.dynamic_slice(atom_mask, (start_idx,), (T,))

            # Shared distances (N, T)
            dr = pos[:, None, :] - r_j[None, :, :]
            dist_sq = jnp.sum(dr ** 2, axis=-1) + 1e-10
            dist = jnp.sqrt(dist_sq)

            # --- Sparse Exclusion Processing ---
            # Instead of a dense (N, N) matrix, we compute the (N, T) exclusion block
            # on the fly from sys.excl_indices and sys.excl_scales.
            # Base scales are 1.0 (everything included)
            vdw_scale_tile = jnp.ones((N, T), dtype=jnp.float32)
            elec_scale_tile = jnp.ones((N, T), dtype=jnp.float32)
            
            # Slice the sparse exclusion data for these T atoms
            t_excl_idx = jax.lax.dynamic_slice(sys.excl_indices, (start_idx, 0), (T, sys.excl_indices.shape[1]))
            t_vdw_scale = jax.lax.dynamic_slice(sys.excl_scales_vdw, (start_idx, 0), (T, sys.excl_scales_vdw.shape[1]))
            t_elec_scale = jax.lax.dynamic_slice(sys.excl_scales_elec, (start_idx, 0), (T, sys.excl_scales_elec.shape[1]))

            # Scatter scales into the (N, T) block
            j_local = jnp.arange(T)
            flat_ii = t_excl_idx.reshape(-1) # (T * max_excl)
            flat_jj = jnp.repeat(j_local, t_excl_idx.shape[1])
            
            vdw_scale_tile = vdw_scale_tile.at[flat_ii, flat_jj].set(t_vdw_scale.reshape(-1))
            elec_scale_tile = elec_scale_tile.at[flat_ii, flat_jj].set(t_elec_scale.reshape(-1))

            # Pair mask (atoms exist and it's not a self-interaction)
            i_indices = jnp.arange(N)[:, None]
            j_indices = jnp.arange(T)[None, :] + start_idx
            not_self = (i_indices != j_indices).astype(jnp.float32)
            pair_mask = (atom_mask[:, None] & m_j[None, :]).astype(jnp.float32) * not_self

            sig_ij = 0.5 * (sigmas[:, None] + s_j[None, :])
            sig_ij_safe = jnp.where(pair_mask > 0, jnp.maximum(sig_ij, 1e-4), 1.0)
            eps_ij = jnp.sqrt(jnp.maximum(epsilons[:, None] * e_j[None, :], 0.0))

            # --- LJ Soft Core (Beutler formulation) ---
            soft_alpha_lj = jnp.float32(0.5) * (1.0 - lam)
            r_over_sig = dist / sig_ij_safe
            r_over_sig_6 = r_over_sig ** 6
            denom_lj = soft_alpha_lj + r_over_sig_6
            
            x_inv6_soft = 1.0 / jnp.maximum(denom_lj, 1e-6)
            e_lj = 4.0 * eps_ij * lam * (x_inv6_soft * x_inv6_soft - x_inv6_soft)
            e_lj = jnp.where(pair_mask > 0, e_lj * vdw_scale_tile, 0.0)

            # --- Coulomb Soft Core ---
            soft_alpha_coul = jnp.float32(2.0) * (1.0 - lam)
            dist_coul = jnp.sqrt(dist_sq + soft_alpha_coul)
            
            qq = charges[:, None] * q_j[None, :] * COULOMB_CONSTANT
            if pme_alpha > 0.0:
                coulomb_term = qq * erfc(pme_alpha * dist_coul) / dist_coul
            else:
                coulomb_term = qq / dist_coul
            e_coul = jnp.where(pair_mask > 0, coulomb_term * elec_scale_tile, 0.0)

            return 0.5 * jnp.sum(e_lj) + 0.5 * jnp.sum(e_coul)

        # Body function for the scan loop (one tile)
        # We explicitly wrap this with unroll=1 to prevent XLA from bloating the graph
        # for a 195-iteration loop with massive intermediates.
        tile_e = _compute_tile_inner(positions, start)
        return carry + tile_e, None

    total_energy, _ = jax.lax.scan(
        tile_energy_outer,
        jnp.array(0.0, dtype=positions.dtype),
        jnp.arange(n_tiles),
        unroll=1,
    )

    return total_energy


def _chunked_lj_only_energy(
    positions: Array,
    sigmas: Array,
    epsilons: Array,
    atom_mask: Array,
    sys: PaddedSystem,
    T: int = 256,
    soft_core_lambda: float = 1.0,
) -> Array:
  """Compute LJ energy only, skipping Coulomb (for EFA integration).

  Uses the same tiling strategy as chunked_explicit_nonbonded_energy but
  excludes the Coulomb term.

  Args:
      positions: (N, 3) atom positions.
      sigmas: (N,) LJ sigma.
      epsilons: (N,) LJ epsilon.
      atom_mask: (N,) boolean mask.
      sys: PaddedSystem with exclusion info.
      T: Tile size.
      soft_core_lambda: Soft-core coupling (1.0 = standard).

  Returns:
      Scalar LJ energy.
  """
  N = positions.shape[0]
  n_tiles = N // T
  lam = jnp.float32(soft_core_lambda)

  def tile_energy_outer(carry, j_idx):
    start = j_idx * T

    @jax.checkpoint
    def _compute_tile_lj_only(pos, start_idx):
      r_j = jax.lax.dynamic_slice(pos, (start_idx, 0), (T, 3))
      s_j = jax.lax.dynamic_slice(sigmas, (start_idx,), (T,))
      e_j = jax.lax.dynamic_slice(epsilons, (start_idx,), (T,))
      m_j = jax.lax.dynamic_slice(atom_mask, (start_idx,), (T,))

      dr = pos[:, None, :] - r_j[None, :, :]
      dist_sq = jnp.sum(dr ** 2, axis=-1) + 1e-10
      dist = jnp.sqrt(dist_sq)

      # Sparse exclusion scales
      vdw_scale_tile = jnp.ones((N, T), dtype=jnp.float32)
      t_excl_idx = jax.lax.dynamic_slice(sys.excl_indices, (start_idx, 0), (T, sys.excl_indices.shape[1]))
      t_vdw_scale = jax.lax.dynamic_slice(sys.excl_scales_vdw, (start_idx, 0), (T, sys.excl_scales_vdw.shape[1]))
      j_local = jnp.arange(T)
      flat_ii = t_excl_idx.reshape(-1)
      flat_jj = jnp.repeat(j_local, t_excl_idx.shape[1])
      vdw_scale_tile = vdw_scale_tile.at[flat_ii, flat_jj].set(t_vdw_scale.reshape(-1))

      # Pair mask
      i_indices = jnp.arange(N)[:, None]
      j_indices = jnp.arange(T)[None, :] + start_idx
      not_self = (i_indices != j_indices).astype(jnp.float32)
      pair_mask = (atom_mask[:, None] & m_j[None, :]).astype(jnp.float32) * not_self

      sig_ij = 0.5 * (sigmas[:, None] + s_j[None, :])
      sig_ij_safe = jnp.where(pair_mask > 0, jnp.maximum(sig_ij, 1e-4), 1.0)
      eps_ij = jnp.sqrt(jnp.maximum(epsilons[:, None] * e_j[None, :], 0.0))

      # LJ Soft Core (Beutler)
      soft_alpha_lj = jnp.float32(0.5) * (1.0 - lam)
      r_over_sig = dist / sig_ij_safe
      r_over_sig_6 = r_over_sig ** 6
      denom_lj = soft_alpha_lj + r_over_sig_6
      x_inv6_soft = 1.0 / jnp.maximum(denom_lj, 1e-6)
      e_lj = 4.0 * eps_ij * lam * (x_inv6_soft * x_inv6_soft - x_inv6_soft)
      e_lj = jnp.where(pair_mask > 0, e_lj * vdw_scale_tile, 0.0)

      return 0.5 * jnp.sum(e_lj)

    tile_e = _compute_tile_lj_only(positions, start)
    return carry + tile_e, None

  total_energy, _ = jax.lax.scan(
      tile_energy_outer,
      jnp.array(0.0, dtype=positions.dtype),
      jnp.arange(n_tiles),
      unroll=1,
  )

  return total_energy


def _total_energy_fn(
    sys: PaddedSystem,
    T: int = 256,
    soft_core_lambda: float = 1.0,
    electrostatic_method: ElectrostaticMethod | str = ElectrostaticMethod.PME,
    n_rff_features: int = 512,
    rff_seed: int = 0,
) -> Array:
    """Internal energy implementation for gradients.

    Args:
        sys: PaddedSystem with topology and parameters.
        T: Tile size for FlashMD.
        soft_core_lambda: Soft-core coupling (1.0 = standard).
        electrostatic_method: EFA or PME (default).
        n_rff_features: Number of RFF features for EFA (default 512).
        rff_seed: PRNG seed for RFF frequency sampling (default 0).

    Returns:
        Scalar energy in kcal/mol.
    """
    if isinstance(electrostatic_method, str):
        electrostatic_method = ElectrostaticMethod(electrostatic_method)

    pos = sys.positions
    safe_charges = jnp.where(sys.atom_mask, sys.charges, jnp.float32(0.0))
    safe_sigmas = jnp.where(sys.atom_mask, sys.sigmas, jnp.float32(1.0))
    safe_epsilons = jnp.where(sys.atom_mask, sys.epsilons, jnp.float32(0.0))

    # EFA path: replace PME with RFF approximation
    if electrostatic_method == ElectrostaticMethod.EFA:
        if soft_core_lambda != 1.0:
            raise ValueError(
                "EFA electrostatics require soft_core_lambda=1.0 "
                "(no alchemical perturbation)."
            )

        # Compute LJ only via chunked loop (modify to skip Coulomb)
        e_lj = _chunked_lj_only_energy(
            pos, safe_sigmas, safe_epsilons, sys.atom_mask, sys, T=T
        )

        # RFF global Coulomb with threaded seed
        rng_key = jax.random.PRNGKey(rff_seed)
        pme_alpha_float = float(sys.pme_alpha)
        omega = rff_frequency_sample(
            alpha=pme_alpha_float,
            n_features=n_rff_features,
            key=rng_key,
        )
        e_coul_rff = erfc_rff_coulomb_energy_diff(
            pos, safe_charges, sys.atom_mask, omega, pme_alpha_float
        )

        # Exclusion correction for bonded pairs
        displacement_fn, _ = pbc.create_periodic_space(sys.box_size)
        n_atoms = pos.shape[0]
        if sys.bonds is not None and sys.bonds.shape[0] > 0:
            excl = topology.find_bonded_exclusions(sys.bonds, n_atoms)
            idx_12, idx_13, idx_14 = excl.idx_12, excl.idx_13, excl.idx_14
        else:
            z = jnp.zeros((0, 2), dtype=jnp.int32)
            idx_12 = idx_13 = idx_14 = z

        # Single exclusion correction call: 1-2/1-3 are fully excluded (scale=0.0),
        # 1-4 are scaled (scale=0.833). Avoids double-subtraction.
        idx_12_13 = jnp.concatenate(
            [idx_12, idx_13] if idx_12.shape[0] > 0 or idx_13.shape[0] > 0
            else [jnp.zeros((0, 2), dtype=jnp.int32), jnp.zeros((0, 2), dtype=jnp.int32)]
        )
        e_excl = efa_exclusion_correction(
            pos,
            safe_charges,
            sys.atom_mask,
            displacement_fn,
            idx_12_13,
            idx_14,
            jnp.float32(0.83333333),
            pme_alpha_float,
        )

        # Short-range erfc(αr)/r for hybrid decomposition:
        # 1/r = erfc(αr)/r [short-range] + erf(αr)/r [long-range RFF]
        e_short_range = efa_short_range_erfc_energy(
            pos,
            safe_charges,
            sys.atom_mask,
            displacement_fn,
            float(sys.nonbonded_cutoff),
            pme_alpha_float,
        )

        e_total = e_lj + e_coul_rff + e_short_range + e_excl

        # Dispersion tail correction (still needed for consistency)
        n_tail = sys.n_real_atoms if sys.n_real_atoms is not None else n_atoms
        e_total += explicit_corrections.lj_dispersion_tail_energy(
            sys.box_size,
            safe_sigmas,
            safe_epsilons,
            float(sys.nonbonded_cutoff),
            n_tail,
        )

        return e_total

    # EFA_LEBEDEV path: deterministic Lebedev quadrature instead of RFF sampling
    if electrostatic_method == ElectrostaticMethod.EFA_LEBEDEV:
        if soft_core_lambda != 1.0:
            raise ValueError(
                "EFA_LEBEDEV electrostatics require soft_core_lambda=1.0 "
                "(no alchemical perturbation)."
            )

        # Compute LJ only via chunked loop
        e_lj = _chunked_lj_only_energy(
            pos, safe_sigmas, safe_epsilons, sys.atom_mask, sys, T=T
        )

        # EFA-Lebedev global Coulomb (deterministic, no seed)
        pme_alpha_float = float(sys.pme_alpha)
        params = efa_lebedev_params(pme_alpha_float, n_freqs=n_rff_features, n_lebedev_pts=26)
        e_coul_efa = efa_lebedev_coulomb_energy(pos, safe_charges, sys.atom_mask, params)

        # Exclusion correction for bonded pairs (same as EFA)
        displacement_fn, _ = pbc.create_periodic_space(sys.box_size)
        n_atoms = pos.shape[0]
        if sys.bonds is not None and sys.bonds.shape[0] > 0:
            excl = topology.find_bonded_exclusions(sys.bonds, n_atoms)
            idx_12, idx_13, idx_14 = excl.idx_12, excl.idx_13, excl.idx_14
        else:
            z = jnp.zeros((0, 2), dtype=jnp.int32)
            idx_12 = idx_13 = idx_14 = z

        idx_12_13 = jnp.concatenate(
            [idx_12, idx_13] if idx_12.shape[0] > 0 or idx_13.shape[0] > 0
            else [jnp.zeros((0, 2), dtype=jnp.int32), jnp.zeros((0, 2), dtype=jnp.int32)]
        )
        e_excl = efa_exclusion_correction(
            pos,
            safe_charges,
            sys.atom_mask,
            displacement_fn,
            idx_12_13,
            idx_14,
            jnp.float32(0.83333333),
            pme_alpha_float,
        )

        # Short-range erfc(αr)/r for hybrid decomposition
        e_short_range = efa_short_range_erfc_energy(
            pos,
            safe_charges,
            sys.atom_mask,
            displacement_fn,
            float(sys.nonbonded_cutoff),
            pme_alpha_float,
        )

        e_total = e_lj + e_coul_efa + e_short_range + e_excl

        # Dispersion tail correction
        n_tail = sys.n_real_atoms if sys.n_real_atoms is not None else n_atoms
        e_total += explicit_corrections.lj_dispersion_tail_energy(
            sys.box_size,
            safe_sigmas,
            safe_epsilons,
            float(sys.nonbonded_cutoff),
            n_tail,
        )

        return e_total

    # Default PME path (unchanged)
    recip_energy_fn = None
    if sys.box_size is not None and sys.pme_alpha > 0:
        mean_l = jnp.mean(jnp.asarray(sys.box_size, dtype=jnp.float64))
        grid_points = int(sys.pme_grid_points)
        grid_spacing = float(mean_l) / float(max(grid_points, 1))
        recip_energy_fn = make_spme_energy_fn(
            box_size=sys.box_size,
            alpha=float(sys.pme_alpha),
            grid_spacing=grid_spacing,
        )

    # Direct space (LJ + damped Coulomb)
    # Passed sys directly to allow sparse exclusion extraction
    e_total = chunked_explicit_nonbonded_energy(
        pos,
        safe_charges,
        safe_sigmas,
        safe_epsilons,
        sys.atom_mask,
        sys,
        pme_alpha=sys.pme_alpha,
        T=T,
        soft_core_lambda=soft_core_lambda,
    )
    # Add PME reciprocal and corrections
    if recip_energy_fn is not None:
        e_total += recip_energy_fn(pos, safe_charges, sys.atom_mask)
        e_total += spme_background_energy(
            safe_charges, sys.atom_mask, sys.pme_alpha, sys.box_size
        )
        displacement_fn, _ = pbc.create_periodic_space(sys.box_size)
        n_atoms = pos.shape[0]
        if sys.bonds is not None and sys.bonds.shape[0] > 0:
            excl = topology.find_bonded_exclusions(sys.bonds, n_atoms)
            idx_12, idx_13, idx_14 = excl.idx_12, excl.idx_13, excl.idx_14
        else:
            z = jnp.zeros((0, 2), dtype=jnp.int32)
            idx_12 = idx_13 = idx_14 = z
        coul_14 = jnp.float32(0.83333333)
        e_total += explicit_corrections.pme_exclusion_correction_energy(
            pos,
            displacement_fn,
            idx_12,
            idx_13,
            idx_14,
            safe_charges,
            float(sys.pme_alpha),
            float(coul_14),
        )
        n_tail = sys.n_real_atoms if sys.n_real_atoms is not None else n_atoms
        e_total += explicit_corrections.lj_dispersion_tail_energy(
            sys.box_size,
            safe_sigmas,
            safe_epsilons,
            float(sys.nonbonded_cutoff),
            n_tail,
        )

    return e_total


def flash_explicit_total_energy(
    sys: PaddedSystem,
    T: int = 256,
    soft_core_lambda: float = 1.0,
    electrostatic_method: ElectrostaticMethod | str = ElectrostaticMethod.PME,
    n_rff_features: int = 512,
    rff_seed: int = 0,
) -> Array:
    """Complete explicit solvent energy: bonded + FlashMD nonbonded + PME.

    This is the correct energy function for minimization. Unlike
    flash_explicit_energy (nonbonded only), this includes all bonded
    terms needed for structural integrity during energy minimization.
    """
    from jax_md import space

    from prolix.batched_energy import (
        _angle_energy_masked,
        _bond_energy_masked,
        _cmap_energy_masked,
        _dihedral_energy_masked,
    )

    pos = sys.positions
    if sys.box_size is not None:
        displacement_fn, _ = pbc.create_periodic_space(sys.box_size)
    else:
        displacement_fn, _ = space.free()

    # --- Bonded terms (O(N), no N² operations) ---
    e_bond = _bond_energy_masked(
        pos, sys.bonds, sys.bond_params, sys.bond_mask, displacement_fn)
    e_ub = _bond_energy_masked(
        pos, sys.urey_bradley_bonds, sys.urey_bradley_params,
        sys.urey_bradley_mask, displacement_fn)
    e_angle = _angle_energy_masked(
        pos, sys.angles, sys.angle_params, sys.angle_mask, displacement_fn)
    e_dih = _dihedral_energy_masked(
        pos, sys.dihedrals, sys.dihedral_params,
        sys.dihedral_mask, displacement_fn)
    e_imp = _dihedral_energy_masked(
        pos, sys.impropers, sys.improper_params,
        sys.improper_mask, displacement_fn)
    e_cmap = _cmap_energy_masked(
        pos, sys.cmap_torsions, sys.cmap_indices,
        sys.cmap_mask, sys.cmap_coeffs, displacement_fn)

    e_bonded = e_bond + e_ub + e_angle + e_dih + e_imp + e_cmap

    # --- Nonbonded terms (FlashMD tiled O(N²/T)) ---
    e_nonbonded = _total_energy_fn(sys, T=T, soft_core_lambda=soft_core_lambda,
                                   electrostatic_method=electrostatic_method,
                                   n_rff_features=n_rff_features,
                                   rff_seed=rff_seed)

    return e_bonded + e_nonbonded


def flash_explicit_energy(
    sys: PaddedSystem,
    T: int = 256,
    soft_core_lambda: float = 1.0,
    electrostatic_method: ElectrostaticMethod | str = ElectrostaticMethod.PME,
    n_rff_features: int = 512,
    rff_seed: int = 0,
) -> Array:
    """Compute explicit solvent nonbonded energy via FlashMD architecture."""
    return _total_energy_fn(sys, T=T, soft_core_lambda=soft_core_lambda,
                            electrostatic_method=electrostatic_method,
                            n_rff_features=n_rff_features,
                            rff_seed=rff_seed)


def flash_explicit_forces(
    sys: PaddedSystem,
    T: int = 256,
    soft_core_lambda: float = 1.0,
    electrostatic_method: ElectrostaticMethod | str = ElectrostaticMethod.PME,
    n_rff_features: int = 512,
    rff_seed: int = 0,
) -> Array:
    """Compute explicit solvent nonbonded forces via FlashMD architecture.

    Includes PME reciprocal-space contributions if box_size and pme_alpha
    are present in the system.

    Returns:
        Forces (N, 3) in kcal/mol/Å. Zero for padded atoms.
    """
    # Use eqx.filter_grad instead of jax.grad to respect static fields (like box_size).
    # This prevents Tracer Errors in the PME reciprocal kernel.
    @eqx.filter_grad
    def _grad_fn(s: PaddedSystem):
        return _total_energy_fn(s, T=T, soft_core_lambda=soft_core_lambda,
                                electrostatic_method=electrostatic_method,
                                n_rff_features=n_rff_features,
                                rff_seed=rff_seed)

    grad_at_sys = _grad_fn(sys)

    # We want the forces on positions: F = -dE/dr
    # eqx.filter_grad returns a PyTree of gradients for all dynamic leaves.
    forces = -grad_at_sys.positions
    return forces * sys.atom_mask[:, None]
